### ISSUE TITLE
属性冲突

### ISSUE THREAD

**Issue by andansky** [7heaven/SHSegmentControl#7]
Error:(1407) Attribute "direction" has already been defined
就是你这个库跟我导入的一库的属性冲突，这个该怎么办？难道只能去改你们两个中的一个的源码才能用？

**Comment by 7heaven** [comment]
Android是直接把attr合并的 没有namespace的概念，所以除非每个项目都给它自己的attr加个类似于xxx_的头 要不很难避免attr重复，我在1.16里面把比较容易和其他项目的attr冲突的名称修改了一下

**Comment by Billxxxx** [comment]
Attribute "cornerRadius" already defined with incompatible format.
还是加一个前缀好点吧
